# [python - What is pyproject.toml file for? - Stack Overflow](https://stackoverflow.com/questions/62983756/what-is-pyproject-toml-file-for)
#https://pycqa.github.io/isort/
#[domdfcoding/yapf-isort: yapf 💌 isort](https://github.com/domdfcoding/yapf-isort)
[tool.isort]
profile = "hug"
skip_glob = ["migrations/*"]
known_third_party=["pytest", "pyjson5","xalpha","pandas","pendulum"]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
lines_after_imports = 2
use_parentheses = true
balanced_wrapping = true
ensure_newline_before_comments = true
line_length = 120
known_flask = ["flask","flask_wtf","wtforms","flask_bcrypt","flask_caching","flask_migrate","flask_sqlalchemy","flask_static_digest","apiflask","flask_praetorian"]
known_test = ["pytest","webtest","factory"]
sections = ["FUTURE","STDLIB","FLASK","TEST","THIRDPARTY","FIRSTPARTY","LOCALFOLDER"]
# ref: https://github.com/scrapinghub/dateparser/issues/1013
[tool.pytest.ini_options]
filterwarnings = ["ignore::pytz_deprecation_shim.PytzUsageWarning","ignore:.*.* is deprecated:DeprecationWarning"]
[tool.yapf]
based_on_style = "pep8"
spaces_before_comment = 2
BLANK_LINES_AROUND_TOP_LEVEL_DEFINITION = 2
split_before_logical_operator = true
BLANK_LINES_BETWEEN_TOP_LEVEL_IMPORTS_AND_VARIABLES = 2
BLANK_LINE_BEFORE_NESTED_CLASS_OR_DEF = true
COLUMN_LIMIT = 120
[tool.pdm]
[[tool.pdm.source]]
name = "pypi"
url = "https://mirrors.aliyun.com/pypi/simple/"
verify_ssl = true

[tool.pdm.dev-dependencies]
test = [
    "pytest>=7.1.3",
]
[project]
name = ""
version = ""
description = ""
authors = [
    {name = "imoyao", email = "immoyao@gmail.com"},
]
dependencies = [
    "apiflask>=1.1.3",
    "importlib-metadata>=5.0.0",
]
requires-python = ">=3.7"
license = {text = "BSD 2-Clause"}
[project.optional-dependencies]

[build-system]
requires = ["pdm-pep517>=1.0.0"]
build-backend = "pdm.pep517.api"
