# -*- coding: utf-8 -*-
"""且慢平台投顾组合元数据注册表。

**单一真相源**：本模块定义「我们跟踪哪些且慢组合、它们叫什么、属于哪一类」，
供 `scripts/seed_advisors.py` 建档、`AdvisorPortfolioSyncJob` 概览回填、
以及后续数据迁移复用。新增 / 调整组合只改这里，不必每次重新调研。

## 数据来源
- 组合清单：2026-09-11 调研的且慢平台组合策略公开查询接口（100 只）
- 官方元数据：且慢 MCP `GetStrategyDetails`，可实时刷新，
  见 `app/services/thermometer/fetchers.py::QiemanFetcher.fetch_strategy_details`

## 字段说明
| 字段 | 含义 | 是否随行情变化 |
|---|---|---|
| `code` | 且慢组合代码（`ZHxxxx` / `LONG_WIN` / `J7` / `WALLET` / `SIxxxx` 多种命名空间） | 否 |
| `name` | 组合名称 | 否 |
| `org_name` | 主理人所属机构 / 平台方 | 否 |
| `host` | 人类主理人（仅个别组合单独调研到，其余为 None） | 否 |
| `risk_level` | 风险等级（与官方「策略风险等级」实测一致） | 否 |
| `product_type` | 产品类型（货币 / 货币+ / 纯债 / 固收+ / 平衡 / 权益(偏股)） | 否 |
| `bucket` | 四笔钱归属（活钱 / 稳钱 / 长钱） | 否 |
| `estab_date` | 成立日期 `YYYY-MM-DD` | 否 |
| `annual_return` | 历史年化(%) | **是** |
| `max_drawdown` | 最大回撤(%) | **是** |
| `volatility` | 波动率(%) | **是** |

## 维护约定
- 三个**随行情变化**的指标（年化 / 回撤 / 波动率）是 `RESEARCH_AS_OF` 当日的调研快照，
  **仅作 seed 兜底**；线上以同步任务实时抓取的值为准（`fetch_strategy_details` 会覆盖）。
- 组合代码命名空间不统一，**禁止**用 `code.startswith('ZH')` 判定平台归属，
  一律以 `AdvisorPortfolio.platform` 为准。
- 顺序沿用调研清单（按四笔钱 / 回撤分组），新增条目追加在末尾即可。
"""

from typing import Optional

#: 平台标识（与 AdvisorPortfolio.platform 取值一致）
QIEMAN_PLATFORM = 'QIEMAN'

#: 上方三个行情指标字段的调研快照日期
RESEARCH_AS_OF = '2026-09-11'

#: 且慢组合元数据。末尾两只（ZH030684 成长五剑、ZH035411 进取派优选）为**历史已建档**组合，
#: 不在 100 只调研清单内，一并收录以保持注册表与库内一致（避免 seed 后被当成「未知组合」）。
QIEMAN_STRATEGIES: tuple[dict, ...] = (
    {
        'code': 'ZH012636',
        'name': '货币三佳',
        'org_name': '盈米',
        'host': None,
        'risk_level': '低风险',
        'product_type': '货币',
        'bucket': '活钱',
        'estab_date': '2017-01-17',
        'annual_return': 2.64,
        'max_drawdown': 0.0,
        'volatility': 0.15,
    },
    {
        'code': 'ZH013136',
        'name': '我要稳稳的幸福',
        'org_name': '交银施罗德',
        'host': None,
        'risk_level': '中低风险',
        'product_type': '固收+',
        'bucket': '稳钱',
        'estab_date': '2017-01-20',
        'annual_return': 4.8,
        'max_drawdown': 2.79,
        'volatility': 2.36,
    },
    {
        'code': 'LONG_WIN',
        'name': '长赢指数投资计划-150份',
        'org_name': '盈米',
        'host': None,
        'risk_level': '中高风险',
        'product_type': '权益(偏股)',
        'bucket': '长钱',
        'estab_date': '2015-07-01',
        'annual_return': 4.68,
        'max_drawdown': 19.79,
        'volatility': 11.09,
    },
    {
        'code': 'ZH099893',
        'name': '花好月圆',
        'org_name': '盈米基金研究院',
        'host': None,
        'risk_level': '低风险',
        'product_type': '货币+',
        'bucket': '稳钱',
        'estab_date': '2021-04-20',
        'annual_return': 2.49,
        'max_drawdown': 0.29,
        'volatility': 0.24,
    },
    {
        'code': 'ZH032680',
        'name': '春华秋实',
        'org_name': '静静聊吧',
        'host': None,
        'risk_level': '中风险',
        'product_type': '固收+',
        'bucket': '长钱',
        'estab_date': '2019-01-02',
        'annual_return': 5.38,
        'max_drawdown': 12.83,
        'volatility': 5.74,
    },
    {
        'code': 'ZH156399',
        'name': '债基优等生',
        'org_name': '中欧财富',
        'host': None,
        'risk_level': '低风险',
        'product_type': None,
        'bucket': '稳钱',
        'estab_date': '2022-12-30',
        'annual_return': 3.02,
        'max_drawdown': 1.04,
        'volatility': 0.72,
    },
    {
        'code': 'ZH037268',
        'name': '富国启明星理财升级',
        'org_name': '富国基金',
        'host': None,
        'risk_level': '中低风险',
        'product_type': '固收+',
        'bucket': '稳钱',
        'estab_date': '2022-02-21',
        'annual_return': 2.93,
        'max_drawdown': 3.51,
        'volatility': 2.97,
    },
    {
        'code': 'ZH032687',
        'name': '风和日丽',
        'org_name': '盈米基金研究院',
        'host': None,
        'risk_level': '中低风险',
        'product_type': '固收+',
        'bucket': '稳钱',
        'estab_date': '2019-01-02',
        'annual_return': 3.56,
        'max_drawdown': 4.7,
        'volatility': 2.79,
    },
    {
        'code': 'J7',
        'name': '简慢投资组合',
        'org_name': '盈米基金',
        'host': None,
        'risk_level': '中风险',
        'product_type': '权益(偏股)',
        'bucket': '长钱',
        'estab_date': '2015-01-05',
        'annual_return': 8.86,
        'max_drawdown': 25.48,
        'volatility': 12.17,
    },
    {
        'code': 'SI000090',
        'name': 'U定投',
        'org_name': '盈米',
        'host': None,
        'risk_level': '中高风险',
        'product_type': '权益(偏股)',
        'bucket': '长钱',
        'estab_date': '2017-07-25',
        'annual_return': 6.13,
        'max_drawdown': 31.35,
        'volatility': 16.45,
    },
    {
        'code': 'ZH006498',
        'name': '价值五剑',
        'org_name': '盈米基金',
        'host': None,
        'risk_level': '中风险',
        'product_type': '权益(偏股)',
        'bucket': '长钱',
        'estab_date': '2016-10-21',
        'annual_return': 10.08,
        'max_drawdown': 40.87,
        'volatility': 16.9,
    },
    {
        'code': 'ZH124499',
        'name': '招商固收+星秀',
        'org_name': '招商基金',
        'host': None,
        'risk_level': '中低风险',
        'product_type': '固收+',
        'bucket': '稳钱',
        'estab_date': '2021-10-20',
        'annual_return': 3.01,
        'max_drawdown': 3.52,
        'volatility': 3.12,
    },
    {
        'code': 'ZH000082',
        'name': '盈米稳健八心八箭',
        'org_name': '盈米',
        'host': None,
        'risk_level': '中风险',
        'product_type': '权益(偏股)',
        'bucket': '长钱',
        'estab_date': '2016-02-01',
        'annual_return': 6.79,
        'max_drawdown': 34.24,
        'volatility': 13.72,
    },
    {
        'code': 'ZH040237',
        'name': '小小的太阳',
        'org_name': '广发基金',
        'host': None,
        'risk_level': '低风险',
        'product_type': '固收+',
        'bucket': '稳钱',
        'estab_date': '2021-08-18',
        'annual_return': 2.6,
        'max_drawdown': 3.23,
        'volatility': 2.7,
    },
    {
        'code': 'ZH152825',
        'name': '启明-中西合璧',
        'org_name': '盈米基金',
        'host': None,
        'risk_level': '中高风险',
        'product_type': '权益(偏股)',
        'bucket': '长钱',
        'estab_date': '2023-10-25',
        'annual_return': 15.58,
        'max_drawdown': 12.79,
        'volatility': 13.85,
    },
    {
        'code': 'WALLET',
        'name': '盈米宝',
        'org_name': '盈米基金',
        'host': None,
        'risk_level': '低风险',
        'product_type': None,
        'bucket': '活钱',
        'estab_date': '2015-01-01',
        'annual_return': None,
        'max_drawdown': None,
        'volatility': None,
    },
    {
        'code': 'ZH006358',
        'name': '安心动盈',
        'org_name': '盈米',
        'host': None,
        'risk_level': '中低风险',
        'product_type': '固收+',
        'bucket': '稳钱',
        'estab_date': '2015-01-22',
        'annual_return': 6.25,
        'max_drawdown': 8.54,
        'volatility': 5.16,
    },
    {
        'code': 'LONG_WIN_S',
        'name': '长赢指数投资计划-S定投',
        'org_name': '盈米',
        'host': None,
        'risk_level': '中高风险',
        'product_type': '权益(偏股)',
        'bucket': '长钱',
        'estab_date': '2017-12-14',
        'annual_return': 4.84,
        'max_drawdown': 30.95,
        'volatility': 16.59,
    },
    {
        'code': 'ZH010292',
        'name': 'Earl二八轮动',
        'org_name': '盈米基金',
        'host': None,
        'risk_level': '中风险',
        'product_type': '权益(偏股)',
        'bucket': '长钱',
        'estab_date': '2016-07-29',
        'annual_return': 4.53,
        'max_drawdown': 33.18,
        'volatility': 15.83,
    },
    {
        'code': 'SI000035',
        'name': '周周同行',
        'org_name': '盈米',
        'host': None,
        'risk_level': '中高风险',
        'product_type': '权益(偏股)',
        'bucket': '长钱',
        'estab_date': '2021-05-11',
        'annual_return': 1.55,
        'max_drawdown': 34.93,
        'volatility': 15.12,
    },
    {
        'code': 'ZH045072',
        'name': '添富权益严选',
        'org_name': '汇添富基金',
        'host': None,
        'risk_level': '中高风险',
        'product_type': '权益(偏股)',
        'bucket': '长钱',
        'estab_date': '2021-12-29',
        'annual_return': 2.05,
        'max_drawdown': 40.4,
        'volatility': 17.3,
    },
    {
        'code': 'ZH000193',
        'name': '巨人指数',
        'org_name': '盈米基金',
        'host': None,
        'risk_level': '中风险',
        'product_type': '权益(偏股)',
        'bucket': '长钱',
        'estab_date': '2016-05-27',
        'annual_return': 3.75,
        'max_drawdown': 44.35,
        'volatility': 17.23,
    },
    {
        'code': 'ZH045531',
        'name': '南方梦想佳',
        'org_name': '南方基金',
        'host': None,
        'risk_level': '中低风险',
        'product_type': None,
        'bucket': '稳钱',
        'estab_date': '2020-07-01',
        'annual_return': 1.99,
        'max_drawdown': 1.24,
        'volatility': 0.66,
    },
    {
        'code': 'ZH045075',
        'name': '马拉松固收增强',
        'org_name': '华夏财富',
        'host': None,
        'risk_level': '中风险',
        'product_type': None,
        'bucket': '稳钱',
        'estab_date': '2020-06-16',
        'annual_return': 3.06,
        'max_drawdown': 6.26,
        'volatility': 3.1,
    },
    {
        'code': 'ZH014271',
        'name': '新锐债券组合',
        'org_name': '盈米基金',
        'host': None,
        'risk_level': '中低风险',
        'product_type': '固收+',
        'bucket': '稳钱',
        'estab_date': '2017-08-15',
        'annual_return': 4.15,
        'max_drawdown': 12.58,
        'volatility': 6.23,
    },
    {
        'code': 'ZH009762',
        'name': '天颐五剑',
        'org_name': '盈米基金',
        'host': None,
        'risk_level': '中低风险',
        'product_type': '固收+',
        'bucket': '长钱',
        'estab_date': '2017-05-31',
        'annual_return': 6.77,
        'max_drawdown': 12.77,
        'volatility': 8.05,
    },
    {
        'code': 'ZH005495',
        'name': '守望者组合',
        'org_name': '盈米基金',
        'host': None,
        'risk_level': '中高风险',
        'product_type': '权益(偏股)',
        'bucket': '长钱',
        'estab_date': '2015-09-01',
        'annual_return': 12.0,
        'max_drawdown': 24.32,
        'volatility': 13.84,
    },
    {
        'code': 'ZH017252',
        'name': '交银赢定投',
        'org_name': '交银施罗德',
        'host': None,
        'risk_level': '中高风险',
        'product_type': '平衡',
        'bucket': '长钱',
        'estab_date': '2022-03-02',
        'annual_return': 4.6,
        'max_drawdown': 27.0,
        'volatility': 14.87,
    },
    {
        'code': 'ZH012926',
        'name': '远足',
        'org_name': '盈米基金',
        'host': '基民柠檬',
        'risk_level': '中高风险',
        'product_type': '权益(偏股)',
        'bucket': '长钱',
        'estab_date': '2017-07-24',
        'annual_return': 13.74,
        'max_drawdown': 32.96,
        'volatility': 18.07,
    },
    {
        'code': 'ZH000129',
        'name': '二八轮动',
        'org_name': '盈米',
        'host': None,
        'risk_level': '中风险',
        'product_type': '权益(偏股)',
        'bucket': '长钱',
        'estab_date': '2014-01-03',
        'annual_return': 14.06,
        'max_drawdown': 35.7,
        'volatility': 17.76,
    },
    {
        'code': 'ZH009664',
        'name': '盈米股基精选组合',
        'org_name': '盈米',
        'host': None,
        'risk_level': '中风险',
        'product_type': '权益(偏股)',
        'bucket': '长钱',
        'estab_date': '2017-05-25',
        'annual_return': 9.89,
        'max_drawdown': 40.35,
        'volatility': 17.83,
    },
    {
        'code': 'ZH000085',
        'name': '静静聊吧',
        'org_name': '静静聊吧',
        'host': None,
        'risk_level': '中风险',
        'product_type': '权益(偏股)',
        'bucket': '长钱',
        'estab_date': '2016-02-04',
        'annual_return': 7.26,
        'max_drawdown': 41.39,
        'volatility': 14.96,
    },
    {
        'code': 'ZH005891',
        'name': '新锐突击组合',
        'org_name': '盈米基金',
        'host': None,
        'risk_level': '中高风险',
        'product_type': '权益(偏股)',
        'bucket': '长钱',
        'estab_date': '2016-09-07',
        'annual_return': 5.57,
        'max_drawdown': 45.94,
        'volatility': 16.41,
    },
    {
        'code': 'ZH010246',
        'name': '银河之力',
        'org_name': '盈米基金',
        'host': None,
        'risk_level': '中风险',
        'product_type': '权益(偏股)',
        'bucket': '长钱',
        'estab_date': '2017-06-27',
        'annual_return': 3.04,
        'max_drawdown': 62.33,
        'volatility': 19.72,
    },
    {
        'code': 'ZH013804',
        'name': '李时珍医药基金组合',
        'org_name': '盈米基金',
        'host': None,
        'risk_level': '高风险',
        'product_type': '权益(偏股)',
        'bucket': '长钱',
        'estab_date': '2017-08-10',
        'annual_return': 6.68,
        'max_drawdown': 62.96,
        'volatility': 26.38,
    },
    {
        'code': 'ZH154241',
        'name': '全天候-永久投资策略',
        'org_name': '盈米基金',
        'host': None,
        'risk_level': '中低风险',
        'product_type': '平衡',
        'bucket': '长钱',
        'estab_date': '2023-12-20',
        'annual_return': 11.96,
        'max_drawdown': 9.16,
        'volatility': 6.88,
    },
    {
        'code': 'ZH119289',
        'name': '绘盈长投计划',
        'org_name': '盈米基金',
        'host': None,
        'risk_level': '中高风险',
        'product_type': '权益(偏股)',
        'bucket': '长钱',
        'estab_date': '2021-10-19',
        'annual_return': 3.54,
        'max_drawdown': 24.72,
        'volatility': 11.54,
    },
    {
        'code': 'ZH044047',
        'name': 'G2组合',
        'org_name': '盈米基金',
        'host': None,
        'risk_level': '中高风险',
        'product_type': '权益(偏股)',
        'bucket': '长钱',
        'estab_date': '2020-05-18',
        'annual_return': 9.57,
        'max_drawdown': 31.21,
        'volatility': 15.13,
    },
    {
        'code': 'SI000186',
        'name': '低估定投计划',
        'org_name': '盈米基金',
        'host': None,
        'risk_level': '中高风险',
        'product_type': None,
        'bucket': '长钱',
        'estab_date': '2023-11-20',
        'annual_return': None,
        'max_drawdown': None,
        'volatility': None,
    },
    {
        'code': 'ZH036707',
        'name': '货基课代表',
        'org_name': '盈米基金研究院',
        'host': None,
        'risk_level': '低风险',
        'product_type': '货币',
        'bucket': '活钱',
        'estab_date': '2019-07-24',
        'annual_return': 2.16,
        'max_drawdown': 0.0,
        'volatility': 0.11,
    },
    {
        'code': 'ZH179123',
        'name': '工银货债灵活基金投顾策略(全市场版)',
        'org_name': '工银瑞信基金',
        'host': None,
        'risk_level': '中低风险',
        'product_type': None,
        'bucket': '稳钱',
        'estab_date': '2026-06-18',
        'annual_return': None,
        'max_drawdown': 0.01,
        'volatility': None,
    },
    {
        'code': 'ZH187337',
        'name': '盈米低波固收+',
        'org_name': '盈米基金',
        'host': None,
        'risk_level': '中低风险',
        'product_type': None,
        'bucket': '稳钱',
        'estab_date': '2026-09-08',
        'annual_return': None,
        'max_drawdown': 0.06,
        'volatility': None,
    },
    {
        'code': 'ZH155932',
        'name': '天马短债',
        'org_name': '盈米基金',
        'host': None,
        'risk_level': '低风险',
        'product_type': None,
        'bucket': '稳钱',
        'estab_date': '2024-03-08',
        'annual_return': 1.71,
        'max_drawdown': 0.19,
        'volatility': 0.19,
    },
    {
        'code': 'ZH121406',
        'name': '货币加',
        'org_name': '广发基金',
        'host': None,
        'risk_level': '低风险',
        'product_type': '货币+',
        'bucket': '稳钱',
        'estab_date': '2021-08-18',
        'annual_return': 2.2,
        'max_drawdown': 0.19,
        'volatility': 0.18,
    },
    {
        'code': 'ZH131352',
        'name': '鹏华稳收优选',
        'org_name': '鹏华基金',
        'host': None,
        'risk_level': '中低风险',
        'product_type': '货币+',
        'bucket': '稳钱',
        'estab_date': '2022-03-16',
        'annual_return': 2.12,
        'max_drawdown': 0.24,
        'volatility': 0.22,
    },
    {
        'code': 'ZH115077',
        'name': '建信梧桐货币增强组合',
        'org_name': '建信投顾姐姐',
        'host': None,
        'risk_level': '中低风险',
        'product_type': '货币+',
        'bucket': '稳钱',
        'estab_date': '2021-09-23',
        'annual_return': 2.06,
        'max_drawdown': 0.31,
        'volatility': 0.19,
    },
    {
        'code': 'ZH183751',
        'name': '东东固收+',
        'org_name': '盈米基金',
        'host': None,
        'risk_level': '中风险',
        'product_type': None,
        'bucket': '稳钱',
        'estab_date': '2026-08-14',
        'annual_return': None,
        'max_drawdown': 0.34,
        'volatility': None,
    },
    {
        'code': 'ZH148406',
        'name': '富国稳稳星稳健理财',
        'org_name': '富国基金',
        'host': None,
        'risk_level': '中低风险',
        'product_type': '固收+',
        'bucket': '稳钱',
        'estab_date': '2023-04-19',
        'annual_return': 2.93,
        'max_drawdown': 0.48,
        'volatility': 0.78,
    },
    {
        'code': 'ZH124520',
        'name': '招商闲钱佳',
        'org_name': '招商基金',
        'host': None,
        'risk_level': '中低风险',
        'product_type': '货币+',
        'bucket': '稳钱',
        'estab_date': '2021-10-20',
        'annual_return': 2.23,
        'max_drawdown': 0.57,
        'volatility': 0.28,
    },
    {
        'code': 'ZH144575',
        'name': '天马稳健',
        'org_name': '盈米基金',
        'host': None,
        'risk_level': '中低风险',
        'product_type': '固收+',
        'bucket': '稳钱',
        'estab_date': '2023-01-13',
        'annual_return': 3.46,
        'max_drawdown': 0.66,
        'volatility': 1.06,
    },
    {
        'code': 'ZH150775',
        'name': '天天收蛋',
        'org_name': '盈米基金',
        'host': None,
        'risk_level': '低风险',
        'product_type': '纯债',
        'bucket': '稳钱',
        'estab_date': '2023-07-20',
        'annual_return': 2.1,
        'max_drawdown': 0.73,
        'volatility': 0.47,
    },
    {
        'code': 'ZH155823',
        'name': '安益派小添利',
        'org_name': '兴证全球基金',
        'host': None,
        'risk_level': '中低风险',
        'product_type': None,
        'bucket': '稳钱',
        'estab_date': '2024-03-05',
        'annual_return': 2.71,
        'max_drawdown': 0.75,
        'volatility': 0.62,
    },
    {
        'code': 'ZH156810',
        'name': '交银债基债利',
        'org_name': '交银施罗德',
        'host': None,
        'risk_level': '中低风险',
        'product_type': None,
        'bucket': '稳钱',
        'estab_date': '2024-01-03',
        'annual_return': 2.65,
        'max_drawdown': 0.78,
        'volatility': 0.71,
    },
    {
        'code': 'ZH124939',
        'name': '博时货币佳-且慢特别版',
        'org_name': '博时基金',
        'host': None,
        'risk_level': '低风险',
        'product_type': '货币+',
        'bucket': '稳钱',
        'estab_date': '2021-12-27',
        'annual_return': 2.01,
        'max_drawdown': 0.78,
        'volatility': 0.23,
    },
    {
        'code': 'ZH155148',
        'name': '日富一日',
        'org_name': '盈米基金',
        'host': None,
        'risk_level': '低风险',
        'product_type': '货币+',
        'bucket': '稳钱',
        'estab_date': '2024-02-01',
        'annual_return': 2.62,
        'max_drawdown': 0.79,
        'volatility': 0.77,
    },
    {
        'code': 'ZH158735',
        'name': '息息相关',
        'org_name': '盈米基金',
        'host': None,
        'risk_level': '中低风险',
        'product_type': None,
        'bucket': '稳钱',
        'estab_date': '2024-06-26',
        'annual_return': 3.44,
        'max_drawdown': 0.91,
        'volatility': 1.36,
    },
    {
        'code': 'ZH144564',
        'name': '中信证券稳健理财加',
        'org_name': '中信证券',
        'host': None,
        'risk_level': '中低风险',
        'product_type': '固收+',
        'bucket': '稳钱',
        'estab_date': '2023-01-12',
        'annual_return': 2.6,
        'max_drawdown': 1.03,
        'volatility': 1.09,
    },
    {
        'code': 'ZH124523',
        'name': '招商月月佳薪',
        'org_name': '招商基金',
        'host': None,
        'risk_level': '中低风险',
        'product_type': '固收+',
        'bucket': '稳钱',
        'estab_date': '2021-10-20',
        'annual_return': 2.4,
        'max_drawdown': 1.12,
        'volatility': 0.75,
    },
    {
        'code': 'ZH174717',
        'name': '融稳投',
        'org_name': '盈米基金',
        'host': None,
        'risk_level': '中低风险',
        'product_type': None,
        'bucket': '稳钱',
        'estab_date': '2026-02-13',
        'annual_return': 1.2,
        'max_drawdown': 1.27,
        'volatility': 2.69,
    },
    {
        'code': 'ZH175554',
        'name': '稳健安盈',
        'org_name': '盈米基金',
        'host': None,
        'risk_level': '中低风险',
        'product_type': None,
        'bucket': '稳钱',
        'estab_date': '2026-03-17',
        'annual_return': None,
        'max_drawdown': 1.45,
        'volatility': None,
    },
    {
        'code': 'ZH125207',
        'name': '理财季季乐',
        'org_name': '广发基金',
        'host': None,
        'risk_level': '低风险',
        'product_type': '固收+',
        'bucket': '稳钱',
        'estab_date': '2021-08-18',
        'annual_return': 2.1,
        'max_drawdown': 1.62,
        'volatility': 1.48,
    },
    {
        'code': 'ZH163296',
        'name': '中欧步步红',
        'org_name': '中欧财富',
        'host': None,
        'risk_level': '中低风险',
        'product_type': None,
        'bucket': '稳钱',
        'estab_date': '2022-12-30',
        'annual_return': 2.89,
        'max_drawdown': 1.62,
        'volatility': 1.55,
    },
    {
        'code': 'ZH143820',
        'name': '锦上添花',
        'org_name': '盈米基金研究院',
        'host': None,
        'risk_level': '低风险',
        'product_type': '固收+',
        'bucket': '稳钱',
        'estab_date': '2022-12-15',
        'annual_return': 3.44,
        'max_drawdown': 1.65,
        'volatility': 1.94,
    },
    {
        'code': 'ZH153951',
        'name': '稳定生财',
        'org_name': '盈米基金',
        'host': None,
        'risk_level': '低风险',
        'product_type': '固收+',
        'bucket': '长钱',
        'estab_date': '2023-12-08',
        'annual_return': 2.27,
        'max_drawdown': 1.72,
        'volatility': 1.63,
    },
    {
        'code': 'ZH142541',
        'name': '迦南磐石',
        'org_name': '盈米基金',
        'host': None,
        'risk_level': '中低风险',
        'product_type': '固收+',
        'bucket': '稳钱',
        'estab_date': '2022-11-08',
        'annual_return': 2.92,
        'max_drawdown': 1.81,
        'volatility': 1.32,
    },
    {
        'code': 'ZH142037',
        'name': '南方安心赢家',
        'org_name': '南方基金',
        'host': None,
        'risk_level': '中低风险',
        'product_type': '固收+',
        'bucket': '稳钱',
        'estab_date': '2022-10-26',
        'annual_return': 3.23,
        'max_drawdown': 1.94,
        'volatility': 1.66,
    },
    {
        'code': 'ZH161416',
        'name': '启明睿-低波指数',
        'org_name': '盈米基金',
        'host': None,
        'risk_level': '中低风险',
        'product_type': None,
        'bucket': '稳钱',
        'estab_date': '2024-11-04',
        'annual_return': 3.73,
        'max_drawdown': 1.94,
        'volatility': 2.55,
    },
    {
        'code': 'ZH028968',
        'name': '智者优选债券资产',
        'org_name': '盈米基金',
        'host': None,
        'risk_level': '低风险',
        'product_type': '纯债',
        'bucket': '稳钱',
        'estab_date': '2018-07-04',
        'annual_return': 3.68,
        'max_drawdown': 2.2,
        'volatility': 0.91,
    },
    {
        'code': 'ZH108375',
        'name': '得之坦然',
        'org_name': '盈米基金',
        'host': None,
        'risk_level': '中低风险',
        'product_type': '纯债',
        'bucket': '稳钱',
        'estab_date': '2021-06-28',
        'annual_return': 3.24,
        'max_drawdown': 2.29,
        'volatility': 0.98,
    },
    {
        'code': 'ZH130772',
        'name': '求稳派小添财',
        'org_name': '兴证全球基金',
        'host': None,
        'risk_level': '中低风险',
        'product_type': '固收+',
        'bucket': '稳钱',
        'estab_date': '2022-03-07',
        'annual_return': 3.5,
        'max_drawdown': 2.36,
        'volatility': 1.81,
    },
    {
        'code': 'ZH124608',
        'name': '招商均衡致远',
        'org_name': '招商基金',
        'host': None,
        'risk_level': '中低风险',
        'product_type': '固收+',
        'bucket': '稳钱',
        'estab_date': '2021-12-09',
        'annual_return': 2.53,
        'max_drawdown': 2.42,
        'volatility': 2.19,
    },
    {
        'code': 'ZH124515',
        'name': '招商慢慢投',
        'org_name': '招商基金',
        'host': None,
        'risk_level': '中低风险',
        'product_type': '固收+',
        'bucket': '稳钱',
        'estab_date': '2021-10-20',
        'annual_return': 2.89,
        'max_drawdown': 2.42,
        'volatility': 2.07,
    },
    {
        'code': 'ZH160350',
        'name': '全球股债商',
        'org_name': '中欧财富',
        'host': None,
        'risk_level': '中低风险',
        'product_type': None,
        'bucket': '长钱',
        'estab_date': '2024-04-30',
        'annual_return': 4.23,
        'max_drawdown': 2.6,
        'volatility': 2.81,
    },
    {
        'code': 'ZH053508',
        'name': '滚雪球组合',
        'org_name': '盈米基金',
        'host': None,
        'risk_level': '中低风险',
        'product_type': '固收+',
        'bucket': '长钱',
        'estab_date': '2019-08-16',
        'annual_return': 4.47,
        'max_drawdown': 2.62,
        'volatility': 2.46,
    },
    {
        'code': 'ZH132208',
        'name': '鹏华小美好',
        'org_name': '鹏华基金',
        'host': None,
        'risk_level': '中低风险',
        'product_type': '固收+',
        'bucket': '稳钱',
        'estab_date': '2022-03-29',
        'annual_return': 3.58,
        'max_drawdown': 2.65,
        'volatility': 2.27,
    },
    {
        'code': 'ZH044651',
        'name': '时间玫瑰',
        'org_name': '盈米基金',
        'host': None,
        'risk_level': '中低风险',
        'product_type': '固收+',
        'bucket': '稳钱',
        'estab_date': '2020-06-04',
        'annual_return': 3.55,
        'max_drawdown': 2.72,
        'volatility': 2.71,
    },
    {
        'code': 'ZH137889',
        'name': '招财猫1号',
        'org_name': '盈米基金',
        'host': None,
        'risk_level': '中低风险',
        'product_type': '纯债',
        'bucket': '稳钱',
        'estab_date': '2022-08-30',
        'annual_return': 3.26,
        'max_drawdown': 2.81,
        'volatility': 2.64,
    },
    {
        'code': 'ZH090141',
        'name': '鑫安利得',
        'org_name': '盈米基金',
        'host': None,
        'risk_level': '中低风险',
        'product_type': '固收+',
        'bucket': '稳钱',
        'estab_date': '2021-03-03',
        'annual_return': 2.61,
        'max_drawdown': 2.86,
        'volatility': 2.31,
    },
    {
        'code': 'ZH152696',
        'name': '盈米银华天玑-暖暖巨蟹座',
        'org_name': '银华基金',
        'host': None,
        'risk_level': '中风险',
        'product_type': '固收+',
        'bucket': '长钱',
        'estab_date': '2023-10-19',
        'annual_return': 3.45,
        'max_drawdown': 2.89,
        'volatility': 2.91,
    },
    {
        'code': 'ZH135897',
        'name': '民生加银固收福禄宝组合',
        'org_name': '民生加银基金',
        'host': None,
        'risk_level': '中低风险',
        'product_type': '固收+',
        'bucket': '稳钱',
        'estab_date': '2022-04-19',
        'annual_return': 3.32,
        'max_drawdown': 2.9,
        'volatility': 2.01,
    },
    {
        'code': 'ZH114462',
        'name': '新锐稳健组合',
        'org_name': '盈米基金',
        'host': None,
        'risk_level': '中低风险',
        'product_type': '固收+',
        'bucket': '长钱',
        'estab_date': '2021-08-13',
        'annual_return': 3.05,
        'max_drawdown': 2.97,
        'volatility': 2.35,
    },
    {
        'code': 'ZH035314',
        'name': '低波动小幸福',
        'org_name': '兴证全球基金',
        'host': None,
        'risk_level': '中低风险',
        'product_type': '固收+',
        'bucket': '稳钱',
        'estab_date': '2022-03-08',
        'annual_return': 3.37,
        'max_drawdown': 2.98,
        'volatility': 2.78,
    },
    {
        'code': 'ZH132910',
        'name': '华安闲钱聪明投',
        'org_name': '华安基金',
        'host': None,
        'risk_level': '中风险',
        'product_type': '固收+',
        'bucket': '稳钱',
        'estab_date': '2022-04-12',
        'annual_return': 2.94,
        'max_drawdown': 2.98,
        'volatility': 3.06,
    },
    {
        'code': 'ZH133230',
        'name': '嘉实稳盈年年红',
        'org_name': '嘉实财富',
        'host': None,
        'risk_level': '低风险',
        'product_type': '固收+',
        'bucket': '稳钱',
        'estab_date': '2022-04-19',
        'annual_return': 3.14,
        'max_drawdown': 3.02,
        'volatility': 2.6,
    },
    {
        'code': 'SI000107',
        'name': '周周有鱼',
        'org_name': '盈米基金',
        'host': None,
        'risk_level': '中低风险',
        'product_type': '固收+',
        'bucket': '长钱',
        'estab_date': '2022-08-11',
        'annual_return': 4.88,
        'max_drawdown': 3.08,
        'volatility': 2.86,
    },
    {
        'code': 'ZH058670',
        'name': '启明睿-低波',
        'org_name': '盈米投顾',
        'host': None,
        'risk_level': '中低风险',
        'product_type': '固收+',
        'bucket': '稳钱',
        'estab_date': '2021-01-04',
        'annual_return': 3.35,
        'max_drawdown': 3.1,
        'volatility': 2.61,
    },
    {
        'code': 'ZH129543',
        'name': '富国守护星稳健理财',
        'org_name': '富国基金',
        'host': None,
        'risk_level': '中低风险',
        'product_type': '固收+',
        'bucket': '稳钱',
        'estab_date': '2022-02-18',
        'annual_return': 2.58,
        'max_drawdown': 3.22,
        'volatility': 2.41,
    },
    {
        'code': 'ZH112601',
        'name': '超级理财加',
        'org_name': '广发基金',
        'host': None,
        'risk_level': '低风险',
        'product_type': '固收+',
        'bucket': '稳钱',
        'estab_date': '2021-08-18',
        'annual_return': 2.47,
        'max_drawdown': 3.25,
        'volatility': 2.26,
    },
    {
        'code': 'ZH143371',
        'name': '基金全磊打之稳中求进',
        'org_name': '盈米基金',
        'host': None,
        'risk_level': '中低风险',
        'product_type': '固收+',
        'bucket': '稳钱',
        'estab_date': '2022-11-30',
        'annual_return': 3.54,
        'max_drawdown': 3.26,
        'volatility': 3.21,
    },
    {
        'code': 'ZH126432',
        'name': '汇添富小确幸',
        'org_name': '汇添富基金',
        'host': None,
        'risk_level': '中低风险',
        'product_type': '固收+',
        'bucket': '稳钱',
        'estab_date': '2022-01-11',
        'annual_return': 2.36,
        'max_drawdown': 3.39,
        'volatility': 2.66,
    },
    {
        'code': 'ZH161034',
        'name': '多元收益',
        'org_name': '兴证全球基金',
        'host': None,
        'risk_level': '中风险',
        'product_type': None,
        'bucket': '长钱',
        'estab_date': '2024-05-30',
        'annual_return': 6.86,
        'max_drawdown': 3.74,
        'volatility': 4.24,
    },
    {
        'code': 'ZH151658',
        'name': '智晖稳健',
        'org_name': '盈米基金',
        'host': None,
        'risk_level': '中低风险',
        'product_type': '固收+',
        'bucket': '稳钱',
        'estab_date': '2023-08-25',
        'annual_return': 3.52,
        'max_drawdown': 3.93,
        'volatility': 3.07,
    },
    {
        'code': 'ZH155420',
        'name': '全球丰收',
        'org_name': '盈米基金',
        'host': None,
        'risk_level': '中低风险',
        'product_type': '平衡',
        'bucket': '长钱',
        'estab_date': '2024-02-20',
        'annual_return': 5.34,
        'max_drawdown': 4.04,
        'volatility': 3.74,
    },
    {
        'code': 'ZH031620',
        'name': '稳益五剑',
        'org_name': '盈米基金',
        'host': None,
        'risk_level': '低风险',
        'product_type': '固收+',
        'bucket': '稳钱',
        'estab_date': '2018-10-31',
        'annual_return': 4.2,
        'max_drawdown': 4.05,
        'volatility': 2.91,
    },
    {
        'code': 'ZH045542',
        'name': '安稳的幸福',
        'org_name': '盈米基金',
        'host': None,
        'risk_level': '中低风险',
        'product_type': '固收+',
        'bucket': '稳钱',
        'estab_date': '2020-07-01',
        'annual_return': 3.93,
        'max_drawdown': 4.21,
        'volatility': 3.72,
    },
    {
        'code': 'ZH171427',
        'name': '基少成多',
        'org_name': '盈米基金',
        'host': None,
        'risk_level': '中低风险',
        'product_type': None,
        'bucket': '稳钱',
        'estab_date': '2025-11-05',
        'annual_return': -0.16,
        'max_drawdown': 4.22,
        'volatility': 3.37,
    },
    {
        'code': 'ZH147147',
        'name': '国泰稳健理财',
        'org_name': '国泰基金',
        'host': None,
        'risk_level': '中低风险',
        'product_type': '固收+',
        'bucket': '稳钱',
        'estab_date': '2023-03-17',
        'annual_return': 3.81,
        'max_drawdown': 4.22,
        'volatility': 3.16,
    },
    {
        'code': 'ZH046291',
        'name': '坚如磐石',
        'org_name': '盈米基金',
        'host': None,
        'risk_level': '中低风险',
        'product_type': '固收+',
        'bucket': '稳钱',
        'estab_date': '2020-07-16',
        'annual_return': 3.75,
        'max_drawdown': 4.23,
        'volatility': 3.33,
    },
    {
        'code': 'ZH165108',
        'name': '饭团全球债',
        'org_name': '盈米基金',
        'host': None,
        'risk_level': '中低风险',
        'product_type': None,
        'bucket': '稳钱',
        'estab_date': '2025-03-27',
        'annual_return': -0.77,
        'max_drawdown': 4.28,
        'volatility': 2.23,
    },
    {
        'code': 'ZH154805',
        'name': '懒猫全球稳健',
        'org_name': '盈米基金',
        'host': None,
        'risk_level': '中低风险',
        'product_type': '固收+',
        'bucket': '长钱',
        'estab_date': '2024-01-15',
        'annual_return': 5.01,
        'max_drawdown': 4.35,
        'volatility': 3.14,
    },
    {
        'code': 'ZH030684',
        'name': '成长五剑',
        'org_name': '盈米基金',
        'host': '二鸟说',
        'risk_level': '中高风险',
        'product_type': '权益(偏股)',
        'bucket': '长钱',
        'estab_date': '2018-09-14',
        'annual_return': 14.95,
        'max_drawdown': 43.28,
        'volatility': 19.08,
    },
    {
        'code': 'ZH035411',
        'name': '进取派优选',
        'org_name': '兴证全球基金',
        'host': None,
        'risk_level': '中高风险',
        'product_type': '权益(偏股)',
        'bucket': '长钱',
        'estab_date': '2022-03-08',
        'annual_return': 4.18,
        'max_drawdown': 28.56,
        'volatility': 17.97,
    },
)


def all_qieman_codes() -> tuple[str, ...]:
    """全部且慢组合代码（保持注册表顺序）。"""
    return tuple(s['code'] for s in QIEMAN_STRATEGIES)


def get_qieman_strategy(code: str) -> Optional[dict]:
    """按代码取单个组合元数据；未收录返回 None。"""
    for s in QIEMAN_STRATEGIES:
        if s['code'] == code:
            return s
    return None
