name: Build Status

on:
  - push

jobs:
  backendunit:
    name: backend check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install Python dependencies
        env:
          FLASK_APP: autoapp.py
#          SECRET_KEY: MPk2WlUArcLeeU_iohzT
#          SEND_FILE_MAX_AGE_DEFAULT: 0
#          BCRYPT_LOG_ROUNDS: 13
#          MAIL_SERVER: smtp.163.com
#          MAIL_USERNAME: FundMate
#          LOG_PATH: /var/log
#          LOG_NAME: run.log
#          MAIL_PASSWORD: 123456
#          MYSQL_USER: foo
#          MYSQL_PASSWORD: bar
        run: |
          cd ./backend
          python -m pip install --upgrade pip
          pip install -r requirements/dev.txt
          flask lint --check
          flask test
  docsunit:
    name: docs lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.2
        with:
          node-version: "12.x"
          registry-url: "https://registry.npmjs.org"
      - name: Install Node dependencies
        run: npm install
      - name: Run Node lints
        run: yarn run lint-md
  frontendunit:
    name: frontend lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.2
        with:
          node-version: "12.x"
          registry-url: "https://registry.npmjs.org"
      - name: Install Node dependencies
        run: |
          cd ./frontend
          yarn install
          yarn run lint
